apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy26
  labels:
    app: autodeploy26
  namespace: namespace-workflow-1714574482313
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy26
  template:
    metadata:
      labels:
        app: autodeploy26
    spec:
      containers:
        - name: autodeploy26
          image: acrworkflow1714574482313.azurecr.io/image-workflow-1714574482313:latest
          ports:
            - containerPort: 5000